spring.application.name=EcoTrackAI

# PostgreSQL Database (Render Environment Variables)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server Port
server.port=${PORT:8080}

# Gemini API Key
gemini.api.key=${GEMINI_API_KEY}