spring.application.name=EcoTrackAI

spring.datasource.url=jdbc:mysql://localhost:3306/ecotrack_ai
spring.datasource.username=root
spring.datasource.password=****

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

gemini.api.key=YOUR_GEMINI_API_KEY